//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9_EF_Crud_usingDB_First_Approch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProduct
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Product_Id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
