// <auto-generated />
namespace _13_Areas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class LoginModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoginModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202412121401242_LoginModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
